//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrasileiraoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPEONATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAMPEONATO()
        {
            this.JOGO = new HashSet<JOGO>();
            this.RESULTADO = new HashSet<RESULTADO>();
            this.RODADA = new HashSet<RODADA>();
            this.TIME_CAMPEONATO = new HashSet<TIME_CAMPEONATO>();
        }

        public CAMPEONATO(string descricao, string historia, int ano, int quantidadeTimes)
        {
            this.descricao = descricao;
            this.historia = historia;
            this.ano = ano;
            this.quantidadeTimes = quantidadeTimes;
        }

        public int id { get; set; }
        public string descricao { get; set; }
        public string historia { get; set; }
        public int ano { get; set; }
        public int quantidadeTimes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOGO> JOGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTADO> RESULTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RODADA> RODADA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIME_CAMPEONATO> TIME_CAMPEONATO { get; set; }
    }
}
