//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrasileiraoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTADO
    {
        public RESULTADO(int idTime, int idRodada, int idCampeonato, int pontos, int saldoGols, int totalFaltas)
        {
            this.idTime = idTime;
            this.idRodada = idRodada;
            this.idCampeonato = idCampeonato;
            this.pontos = pontos;
            this.saldoGols = saldoGols;
            this.totalFaltas = totalFaltas;
        }

        public int id { get; set; }
        public int idTime { get; set; }
        public int idRodada { get; set; }
        public int idCampeonato { get; set; }
        public int pontos { get; set; }
        public int saldoGols { get; set; }
        public int totalFaltas { get; set; }
    
        public virtual CAMPEONATO CAMPEONATO { get; set; }
        public virtual RODADA RODADA { get; set; }
        public virtual TIME TIME { get; set; }
    }
}
