//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrasileiraoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIME()
        {
            this.JOGO = new HashSet<JOGO>();
            this.JOGO1 = new HashSet<JOGO>();
            this.RESULTADO = new HashSet<RESULTADO>();
            this.TIME_CAMPEONATO = new HashSet<TIME_CAMPEONATO>();
        }

        public TIME(string nome, string historia, int? anoFundacao, int? quantidadeTorcedores, int? quantidadeTitulos)
        {
            this.nome = nome;
            this.historia = historia;
            this.anoFundacao = anoFundacao;
            this.quantidadeTorcedores = quantidadeTorcedores;
            this.quantidadeTitulos = quantidadeTitulos;
        }

        public int id { get; set; }
        public string nome { get; set; }
        public string historia { get; set; }
        public Nullable<int> anoFundacao { get; set; }
        public Nullable<int> quantidadeTorcedores { get; set; }
        public Nullable<int> quantidadeTitulos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOGO> JOGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOGO> JOGO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTADO> RESULTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIME_CAMPEONATO> TIME_CAMPEONATO { get; set; }
    }
}
