//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrasileiraoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME_CAMPEONATO
    {
        public TIME_CAMPEONATO(int idTime, int idCampeonato)
        {
            this.idTime = idTime;
            this.idCampeonato = idCampeonato;
        }

        public int id { get; set; }
        public int idTime { get; set; }
        public int idCampeonato { get; set; }
    
        public virtual CAMPEONATO CAMPEONATO { get; set; }
        public virtual TIME TIME { get; set; }
    }
}
