//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrasileiraoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO(string usuario1, string senha)
        {
            this.usuario1 = usuario1;
            this.senha = senha;
        }

        public int id { get; set; }
        public string usuario1 { get; set; }
        public string senha { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
    }
}
